import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '戦略一覧',
      link: {type: 'doc', id: 'strategies/index'},
      items: [{type: 'autogenerated', dirName: 'strategies'}],
    },
    {
      type: 'category',
      label: '指針',
      link: {type: 'doc', id: 'doctrines/index'},
      items: [{type: 'autogenerated', dirName: 'doctrines'}],
    },
    {
      type: 'category',
      label: '戦略ガイド',
      link: {type: 'doc', id: 'strategy-guides/index'},
      items: [{type: 'autogenerated', dirName: 'strategy-guides'}],
    },
    {
      type: 'category',
      label: '気候パターン',
      link: {type: 'doc', id: 'climatic-patterns/index'},
      items: [{type: 'autogenerated', dirName: 'climatic-patterns'}],
    },
    {
      type: 'category',
      label: '用語集',
      link: {type: 'doc', id: 'terms/index'},
      items: [{type: 'autogenerated', dirName: 'terms'}],
    },
    {
      type: 'category',
      label: 'リーダーシップスキル',
      link: {type: 'doc', id: 'leadership-skills/index'},
      items: [{type: 'autogenerated', dirName: 'leadership-skills'}],
    },
    {
      type: 'category',
      label: '参考書籍',
      link: {type: 'doc', id: 'books/index'},
      items: [{type: 'autogenerated', dirName: 'books'}],
    },
  ],
};

export default sidebars;
